### ISSUE TITLE
rbenv: no such command 'use'

### ISSUE THREAD

**Issue by ntalbott** [rkh/rbenv-use#1]
The plugin didn't work for me until I renamed `bin/rbenv-sh-use` to `bin/rbenv-use`. I'm on rbenv 0.3.0.

Sweet work BTW - it's going to save me a ton of time!

**Comment by rkh** [comment]
If you do that, it won't work except for `--global` and `--local`. You'll have to run `rbenv init -` again to get it working (i.e. you'll probably have to open a new shell).

**Comment by ntalbott** [comment]
Turns out renaming it didn't work: if I do that rbenv sees the command, but I just end up getting the command echo'd to the console rather than actually run. So I renamed it back, and then rbenv couldn't find it again.

But now I've gone back and tried again a few hours later, and rbenv sees the use command now. No idea what changed, but maybe I needed to exit and re-load my terminal? Anyhow, sorry to bother you!
