### ISSUE TITLE
rbenv: no such command `use' error

### ISSUE THREAD

**Issue by ianheggie** [rkh/rbenv-use#2]
$ rbenv --version

rbenv 0.4.0-13-ge3f72eb

$ rbenv use 1.9.3
rbenv: no such command `use'

$ rbenv versions
  system
  1.8.7-p370
- 1.8.7-p371 (set by /home/ianh/tmp/.ruby-version)
  1.9.3-p374
  1.9.3-p385

**Comment by rkh** [comment]
Did you set up this plugin properly? What does `ls "$(rbenv root)/plugins"` output?

**Comment by ianheggie** [comment]
Fixed by updating rbenv and rbenv-build!

ianh@abe:~/.rbenv(master)$ rbenv root
/home/ianh/.rbenv

ianh@abe:~/.rbenv(master)$ ls "$(rbenv root)/plugins"
rbenv-binstubs  rbenv-env  rbenv-gemset  rbenv-update  rbenv-use  rbenv-vars  rbenv-whatis  ruby-build

I had updated not long ago, but I did a fresh rbenv update (which updated rebvn from e3f72eb to 0d1f1d0
and updates rbenv-build) and the results changed to:

$ rbenv use 1.9.3
rbenv: version `1.9.3-p392' not installed

$ rbenv install 1.9.3-p392
(compile messages)

$ rbenv use 1.9.3

$ rbenv version
1.9.3-p392 (set by RBENV_VERSION environment variable)

$ rbenv use 1.8.7

$ rbenv version
1.8.7-p371 (set by RBENV_VERSION environment variable)
